#!/usr/bin/env ruby

puts "Setting up a new blog..."

puts "Cleaning posts"

`rm -rf posts/media`
`rm posts/*`

puts "Cleaning layout/style"

`rm public/images/*`

`rm views/layout.haml`
`cp views/layout.haml.example views/layout.haml`

`rm public/stylesheets/application.css`
`cp public/stylesheets/application.css.example public/stylesheets/application.css`

puts "Creating your first post"

`touch posts/first-post.text`
`echo "# Post title\n\n - published 2014-09-12 12:00\n - tags: example\n\nThis is an example post." > posts/first-post.text`

puts "\nDone!"